In [1]:
import pandas as pd
diabetes = pd.read_csv('pima-indians-diabetes.csv')
diabetes.head()

,# 1. Number of times pregnant,# 2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test,# 3. Diastolic blood pressure (mm Hg),# 4. Triceps skin fold thickness (mm),# 5. 2-Hour serum insulin (mu U/ml),# 6. Body mass index (weight in kg/(height in m)^2),# 7. Diabetes pedigree function,# 8. Age (years),# 9. Class variable (0 or 1)
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [8]:
#limpando os dados
cols_to_norm = ['Number_pregnant','glucose_concentration',
                'Blood_pressure', 'triceps', 'insulin', 'BMI','Pedigree']
diabetes[cols_to_norm]=diabetes[cols_to_norm].apply(lambda x: (x-x.min())/(x.max()-x.min()))
diabetes.head()

SyntaxError: invalid syntax (<ipython-input-8-0b2e8828d926>, line 4)